# Generated by Django 3.0.5 on 2020-04-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_auto_20200427_1551'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reply', models.CharField(max_length=600)),
                ('chapter_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chapter', to='courses.Chapter')),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='courses.Courses')),
                ('student_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_accounts', to='user_accounts.User_accounts')),
            ],
        ),
    ]
