# Generated by Django 3.0.5 on 2020-05-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20200428_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='reply',
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('discussion_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Discussion', to='discussion.Discussion')),
            ],
        ),
    ]
