# Generated by Django 3.0.5 on 2020-06-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200625_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_category',
            new_name='Clog_Category',
        ),
    ]
