# Generated by Django 3.0.5 on 2020-06-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200625_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Clog_Category',
            new_name='Blog_Category',
        ),
    ]
