# Generated by Django 3.0.5 on 2020-06-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200625_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Blog_Category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_category'),
        ),
    ]
