# Generated by Django 3.0.5 on 2020-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='videos',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
