# Generated by Django 3.0.5 on 2020-04-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200427_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
