# Generated by Django 3.0.5 on 2020-04-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_discussion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
