# Generated by Django 3.0.5 on 2020-04-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_enroll_details',
            name='details',
        ),
        migrations.RemoveField(
            model_name='course_enroll_details',
            name='no_of_topic',
        ),
        migrations.RemoveField(
            model_name='course_enroll_details',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='no_of_topic',
        ),
    ]
