# Generated by Django 3.0.5 on 2020-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200428_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
