# Generated by Django 3.0.5 on 2020-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_ebooks_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='offerprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
