# Generated by Django 3.0.5 on 2020-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200503_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
