# Generated by Django 3.0.5 on 2020-06-20 16:55

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200504_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
